import type {Messages} from '../../types'
import type es from '../../es/gitparts/agent'

const en: Messages<typeof es> = {
    loading: 'Reading the repository’s agent setup…',
    heading: 'What this repository offers an agent',
    reloadTitle: 'Re-reads .claude/ and the instruction files — handy after creating a skill or a CLAUDE.md',
    defaultAgent: 'Default agent',
    defaultAgentTitle: 'Which assistant opens sessions from this repository when you use Ask. If none is chosen, you’re asked each time.',
    askEachTime: 'Ask each time',
    instructions: {
        title: 'Project instructions',
        openTitle: (p) => `Opens ${p.file} in the editor. Read by ${p.agents}.`,
        missingTitle: (p) =>
            `${p.file} doesn’t exist in this repository, so ${p.agents} starts here without any project instructions. Opening it creates it empty so you can write it.`,
        missingTag: ' — missing',
        noneAtAll: 'This repository has no instruction files: any agent you open here starts without project context.',
        someMissing: (p) =>
            `${p.files} ${p.fileCount > 1 ? 'are' : 'is'} missing — ${p.agents} ${p.agentCount > 1 ? 'don’t' : 'doesn’t'} read the other agents’ files.`,
    },
    skills: 'Skills',
    askSkillPrompt: (p) => `Use the "${p.name}" skill to `,
    subagents: 'Subagents',
    commands: 'Commands',
    nothing: 'No skills, subagents or commands defined — neither in this repository nor in your personal folder.',
    usage: {
        title: (p) => `Token usage · ${p.days} days`,
        unknownPlan: 'unknown plan',
        tokensDetail: (p) => `${p.total} tokens in ${p.messages} responses`,
        tokens: (p) => `${p.n} tokens`,
        conversationsTitle: 'Conversations recorded by the CLI on this machine',
        conversations: 'Conversations:',
        stepsTitle: 'Steps (agent work turns) summed across all conversations',
        steps: 'Steps:',
        repoConversationsTitle: 'Conversations whose workspace includes this repository',
        thisRepo: 'This repo:',
        repoActivity: (p) => `${p.conversations} conv · ${p.steps} steps`,
        lastUsed: (p) => `last used: ${p.when}`,
        repoTokensDetail: (p) => `${p.total} tokens in ${p.messages} responses on this repository`,
        cacheTitle: 'How much of the INPUT tokens came from the cache instead of being reprocessed. It’s the only number here you can act on: the higher, the cheaper a long session.',
        cache: 'Cache:',
        outputTitle: 'Tokens generated by the model. The most expensive of the four kinds.',
        output: 'Output:',
        footnote: 'Limit bars are the percentage each provider’s server calculated and its CLI cached on this machine: they’re shown as-is, with the time they were measured — they aren’t live. Usage percentages (by model, cache, this repo) are shares of what was spent, not of a cap.',
    },
    mcp: {
        title: 'MCP servers',
        none: (p) =>
            `No agent has MCP servers configured for this repository. Checked ${p.looked} locations (${p.present} exist).`,
        addTitle: 'Adds an MCP server to one of the config files the app can write',
        add: 'Add server',
        fileTitle: 'Which file it’s written to. Files not listed aren’t edited from the app.',
        namePlaceholder: 'name (e.g. github)',
        commandPlaceholder: 'command (e.g. npx)',
        argsPlaceholder: 'space-separated arguments',
        envPlaceholder: 'env: KEY=value, OTHER=value',
        envTitle: 'Server environment variables. They’re written to YOUR config file in plain text, which is how the CLI reads them — mini-tools doesn’t store or manage them.',
        serverTitle: (p) =>
            `${p.target}\n\nRead by ${p.agent} · ${p.project ? 'only in this repository' : 'in any repository on this machine'}\nDefined in ${p.source}`,
        remote: 'remote',
        envKeysTitle: 'Names of the environment variables this server receives. Their values never leave the backend.',
        envKeys: (p) => `env: ${p.keys}`,
        removeTitle: (p) =>
            `Removes "${p.name}" from ${p.source}. A .mini-tools.bak copy is left next to it before touching the file.`,
        removeConfirmTitle: (p) => `Remove "${p.name}"`,
        removeConfirm: (p) =>
            `It will be removed from ${p.source}. The agent loses that tool. A .mini-tools.bak copy is left next to it before writing, and the rest of the file isn’t touched.`,
        removeLabel: 'Remove',
    },
    personal: 'personal',
    collapseSection: 'Collapse this section',
    expandSection: (p) => `Expand — ${p.count} items`,
    entry: {
        askTitle: (p) => `Asks the agent to use "${p.name}" and leaves the prompt ready for you to finish`,
        personalTitle: (p) =>
            `${p.path} — it’s in your personal folder, not the repository: your agents on this machine see it, the rest of the team doesn’t`,
        openTitle: (p) => `${p.path} — click to open it in the editor`,
    },
}
export default en
