package sshconn

import (
	"encoding/base64"
	"fmt"
	"io"
	"net"
	"os"
	"sync"

	"golang.org/x/crypto/ssh"
	"golang.org/x/crypto/ssh/agent"
)

// EmitFunc mirrors query.EmitFunc/redisquery.EmitFunc's shape — injected by
// app.go's startup(), never runtime.EventsEmit called directly from this
// package. See .claude/skills/mini-tools-patterns/SKILL.md's Redis section
// for why the executors never own the Wails runtime import themselves.
type EmitFunc func(event string, data interface{})

// Event is emitted on the connID-named Wails event for an open terminal
// session — connID doubles as the event name, same pattern as
// query.Event/redisquery.Event's queryID (frontend subscribes with
// EventsOn(connId, ...) before calling OpenSSHTerminal, avoiding the race
// between the first emit and the subscription).
type Event struct {
	Type string `json:"type"` // "data" | "closed" | "error"
	// Data is base64-encoded raw bytes read from the PTY. The remote shell
	// can emit non-UTF8 bytes (e.g. catting a binary file), which would
	// break JSON string encoding if sent as-is — base64 avoids that at the
	// cost of a decode step on the frontend before term.write().
	Data  string `json:"data,omitempty"`
	Error string `json:"error,omitempty"`
}

const readChunkSize = 4096

type session struct {
	client    *ssh.Client
	sshSess   *ssh.Session
	stdin     io.WriteCloser
	agentConn net.Conn // non-nil only when agent forwarding is active
}

// SessionManager holds one interactive PTY session per connID — not a
// reusable pool like db.PoolManager/db.RedisPoolManager (see package doc).
type SessionManager struct {
	mu       sync.Mutex
	sessions map[string]*session
	emit     EmitFunc
}

func NewSessionManager(emit EmitFunc) *SessionManager {
	return &SessionManager{sessions: make(map[string]*session), emit: emit}
}

// Open dials dsn, requests a PTY-backed shell, and starts a goroutine that
// streams its combined stdout/stderr back as Event{Type:"data"} on the
// connID-named event until the remote shell exits or the connection drops
// (Event{Type:"closed"}). Any session already open for connID is replaced
// (closed first) — a terminal tab only ever calls this once per (re)open.
func (m *SessionManager) Open(connID, dsn string, cols, rows int) error {
	_ = m.Close(connID)

	cp, err := parseDSN(dsn)
	if err != nil {
		return err
	}
	config, err := clientConfig(cp)
	if err != nil {
		return err
	}

	client, err := ssh.Dial("tcp", cp.addr, config)
	if err != nil {
		return fmt.Errorf("sshconn: conectando: %w", err)
	}

	sshSess, err := client.NewSession()
	if err != nil {
		client.Close()
		return fmt.Errorf("sshconn: abriendo sesión: %w", err)
	}

	var agentConn net.Conn
	if cp.agentForwarding {
		agentConn, err = forwardAgent(client, sshSess)
		if err != nil {
			sshSess.Close()
			client.Close()
			return err
		}
	}

	if err := sshSess.RequestPty("xterm-256color", rows, cols, ssh.TerminalModes{
		ssh.ECHO:          1,
		ssh.TTY_OP_ISPEED: 14400,
		ssh.TTY_OP_OSPEED: 14400,
	}); err != nil {
		closeAgentConn(agentConn)
		sshSess.Close()
		client.Close()
		return fmt.Errorf("sshconn: solicitando pty: %w", err)
	}

	stdin, err := sshSess.StdinPipe()
	if err != nil {
		closeAgentConn(agentConn)
		sshSess.Close()
		client.Close()
		return fmt.Errorf("sshconn: abriendo stdin: %w", err)
	}
	// With a PTY allocated, the remote shell's controlling terminal already
	// merges the stdout/stderr of everything running under it — StdoutPipe
	// alone is enough, no separate stderr reader needed (same as any real
	// interactive SSH terminal).
	stdout, err := sshSess.StdoutPipe()
	if err != nil {
		closeAgentConn(agentConn)
		sshSess.Close()
		client.Close()
		return fmt.Errorf("sshconn: abriendo stdout: %w", err)
	}

	if err := sshSess.Shell(); err != nil {
		closeAgentConn(agentConn)
		sshSess.Close()
		client.Close()
		return fmt.Errorf("sshconn: iniciando shell: %w", err)
	}

	m.mu.Lock()
	m.sessions[connID] = &session{client: client, sshSess: sshSess, stdin: stdin, agentConn: agentConn}
	m.mu.Unlock()

	go m.streamOutput(connID, stdout)

	return nil
}

func (m *SessionManager) streamOutput(connID string, stdout io.Reader) {
	buf := make([]byte, readChunkSize)
	for {
		n, err := stdout.Read(buf)
		if n > 0 {
			m.emit(connID, Event{Type: "data", Data: base64.StdEncoding.EncodeToString(buf[:n])})
		}
		if err != nil {
			break
		}
	}
	m.emit(connID, Event{Type: "closed"})
	_ = m.Close(connID)
}

// Write forwards data (keystrokes/paste, generated by xterm.js — always
// valid text/ANSI sequences) to connID's shell stdin.
func (m *SessionManager) Write(connID, data string) error {
	s := m.get(connID)
	if s == nil {
		return fmt.Errorf("sshconn: no hay una sesión abierta para %q", connID)
	}
	_, err := s.stdin.Write([]byte(data))
	return err
}

// Resize reflows connID's PTY after the frontend's xterm.js FitAddon
// recomputes cols/rows.
func (m *SessionManager) Resize(connID string, cols, rows int) error {
	s := m.get(connID)
	if s == nil {
		return fmt.Errorf("sshconn: no hay una sesión abierta para %q", connID)
	}
	return s.sshSess.WindowChange(rows, cols)
}

// Close tears down connID's session, if any is open. Idempotent — safe to
// call from both the explicit CloseSSHTerminal binding (terminal tab
// closed) and streamOutput's own cleanup on remote EOF.
func (m *SessionManager) Close(connID string) error {
	m.mu.Lock()
	s, ok := m.sessions[connID]
	if !ok {
		m.mu.Unlock()
		return nil
	}
	delete(m.sessions, connID)
	m.mu.Unlock()

	s.sshSess.Close()
	s.client.Close()
	closeAgentConn(s.agentConn)
	return nil
}

// CloseAll closes every open session — used on app shutdown.
func (m *SessionManager) CloseAll() {
	m.mu.Lock()
	ids := make([]string, 0, len(m.sessions))
	for id := range m.sessions {
		ids = append(ids, id)
	}
	m.mu.Unlock()

	for _, id := range ids {
		_ = m.Close(id)
	}
}

func (m *SessionManager) get(connID string) *session {
	m.mu.Lock()
	defer m.mu.Unlock()
	return m.sessions[connID]
}

func closeAgentConn(c net.Conn) {
	if c != nil {
		c.Close()
	}
}

// forwardAgent connects to the local ssh-agent (via SSH_AUTH_SOCK, a Unix
// socket) and forwards it to the remote host so commands run there can use
// it for onward auth (e.g. `git clone` of another host, `ssh` a further
// jump). Unix-only for now (Windows' agent uses a named pipe, not
// SSH_AUTH_SOCK) — out of scope for v1, same "documented, not silently
// missing" precedent as redisConnector's sentinel-auth scoping note.
func forwardAgent(client *ssh.Client, sess *ssh.Session) (net.Conn, error) {
	sock := os.Getenv("SSH_AUTH_SOCK")
	if sock == "" {
		return nil, fmt.Errorf("sshconn: agent forwarding solicitado pero SSH_AUTH_SOCK no está seteado (no hay un ssh-agent local corriendo)")
	}
	conn, err := net.Dial("unix", sock)
	if err != nil {
		return nil, fmt.Errorf("sshconn: conectando al ssh-agent local: %w", err)
	}
	ag := agent.NewClient(conn)
	if err := agent.ForwardToAgent(client, ag); err != nil {
		conn.Close()
		return nil, fmt.Errorf("sshconn: forwarding del ssh-agent: %w", err)
	}
	if err := agent.RequestAgentForwarding(sess); err != nil {
		conn.Close()
		return nil, fmt.Errorf("sshconn: solicitando agent forwarding: %w", err)
	}
	return conn, nil
}
