// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {updatecheck} from '../models';
import {vault} from '../models';
import {explain} from '../models';
import {db} from '../models';
import {main} from '../models';
import {sftpx} from '../models';

export function AddRedisSetMember(arg1:string,arg2:string,arg3:string):Promise<void>;

export function AddRedisZSetMember(arg1:string,arg2:string,arg3:string,arg4:number):Promise<void>;

export function AppVersion():Promise<string>;

export function BackupVault(arg1:string):Promise<string>;

export function BeginTransaction(arg1:string):Promise<void>;

export function CancelQuery(arg1:string):Promise<void>;

export function CancelRedisCommand(arg1:string):Promise<void>;

export function CancelSftpTransfer(arg1:string):Promise<void>;

export function CheckForUpdate():Promise<updatecheck.Info>;

export function ChmodSftpPath(arg1:string,arg2:string,arg3:number):Promise<void>;

export function ClearQueryHistory(arg1:string):Promise<void>;

export function ClearRecentFiles():Promise<void>;

export function CloseSSHTerminal(arg1:string):Promise<void>;

export function CloseSftpBrowse(arg1:string):Promise<void>;

export function CommitTransaction(arg1:string):Promise<void>;

export function CreateFolder(arg1:string,arg2:string,arg3:string):Promise<vault.Folder>;

export function CreateSshSnippet(arg1:string,arg2:string):Promise<vault.SshSnippet>;

export function DeleteConnection(arg1:string):Promise<void>;

export function DeleteFolder(arg1:string):Promise<void>;

export function DeleteQueryHistoryEntry(arg1:string):Promise<void>;

export function DeleteRedisHashField(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DeleteRedisKey(arg1:string,arg2:string):Promise<void>;

export function DeleteSftpPath(arg1:string,arg2:string):Promise<void>;

export function DeleteSshSnippet(arg1:string):Promise<void>;

export function DisconnectConnection(arg1:string):Promise<void>;

export function ExecuteQuery(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<void>;

export function ExecuteRedisCommand(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ExplainQuery(arg1:string,arg2:string,arg3:boolean):Promise<explain.Plan>;

export function ExportConnectionConfig(arg1:string):Promise<string>;

export function ExportRedisKeys(arg1:string,arg2:Array<string>):Promise<Array<db.RedisKeyExport>>;

export function ExportResult(arg1:Array<string>,arg2:Array<any>,arg3:string):Promise<string>;

export function ExportSchemaDDL(arg1:string,arg2:string):Promise<string>;

export function ExportTableDDL(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GenerateProjectDocs(arg1:string,arg2:string,arg3:string):Promise<boolean>;

export function GetConnectionForEdit(arg1:string):Promise<main.ConnectionEditInfo>;

export function GetObjectDDL(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number):Promise<string>;

export function GetRedisKeyInfo(arg1:string,arg2:string):Promise<db.RedisKeyInfo>;

export function GetRedisKeyValue(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number,arg6:number):Promise<db.RedisValue>;

export function GetRedisStats(arg1:string):Promise<db.RedisStats>;

export function GetSchemaMetadata(arg1:string,arg2:boolean):Promise<db.SchemaMetadata>;

export function GetSettings():Promise<vault.Settings>;

export function HasOpenTransaction(arg1:string):Promise<boolean>;

export function InitializeVault(arg1:string):Promise<void>;

export function IsVaultInitialized():Promise<boolean>;

export function ListConnections():Promise<Array<vault.ConnectionSummary>>;

export function ListExplainHistory(arg1:string,arg2:number):Promise<Array<vault.ExplainHistoryEntry>>;

export function ListFolders():Promise<Array<vault.Folder>>;

export function ListQueryHistory(arg1:string,arg2:number):Promise<Array<vault.HistoryEntry>>;

export function ListRecentFiles():Promise<Array<vault.RecentFile>>;

export function ListRedisKeys(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number):Promise<db.RedisScanPage>;

export function ListSchemas(arg1:string,arg2:boolean):Promise<Array<string>>;

export function ListSchemasForNewConnection(arg1:main.ConnectionInput):Promise<Array<string>>;

export function ListSftpDir(arg1:string,arg2:string):Promise<Array<sftpx.FileEntry>>;

export function ListSshSnippets():Promise<Array<vault.SshSnippet>>;

export function MakeSftpDir(arg1:string,arg2:string):Promise<void>;

export function MoveConnectionToFolder(arg1:string,arg2:string):Promise<void>;

export function MoveFolder(arg1:string,arg2:string):Promise<void>;

export function MoveSshSnippetToFolder(arg1:string,arg2:string):Promise<void>;

export function OpenSQLFileDialog():Promise<main.FileContent>;

export function OpenSQLFilePath(arg1:string):Promise<main.FileContent>;

export function OpenSSHTerminal(arg1:string,arg2:number,arg3:number):Promise<void>;

export function OpenSftpBrowse(arg1:string,arg2:string):Promise<string>;

export function PickAutoBackupFolder():Promise<string>;

export function PickVaultBackupFile(arg1:string):Promise<string>;

export function PickVaultBackupFileFirstRun():Promise<string>;

export function PushRedisListValue(arg1:string,arg2:string,arg3:string):Promise<void>;

export function RegenerateProjectDocs(arg1:string,arg2:string,arg3:string):Promise<void>;

export function RemoveRedisListIndex(arg1:string,arg2:string,arg3:number):Promise<void>;

export function RemoveRedisSetMember(arg1:string,arg2:string,arg3:string):Promise<void>;

export function RemoveRedisZSetMember(arg1:string,arg2:string,arg3:string):Promise<void>;

export function RenameFolder(arg1:string,arg2:string):Promise<void>;

export function RenameSftpPath(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ReorderFolder(arg1:string,arg2:string):Promise<void>;

export function ResizeSSHTerminal(arg1:string,arg2:number,arg3:number):Promise<void>;

export function RestoreVaultBackupFirstRun(arg1:string,arg2:string):Promise<void>;

export function RestoreVaultBackupFromFile(arg1:string,arg2:string):Promise<void>;

export function RollbackTransaction(arg1:string):Promise<void>;

export function SaveConnection(arg1:main.ConnectionInput,arg2:boolean):Promise<vault.ConnectionSummary>;

export function SaveDDLToFile(arg1:string,arg2:string):Promise<string>;

export function SaveSQLFile(arg1:string,arg2:string):Promise<void>;

export function SaveSQLFileAs(arg1:string,arg2:string):Promise<string>;

export function SetAutoBackupEnabled(arg1:boolean):Promise<void>;

export function SetAutoBackupIntervalHours(arg1:number):Promise<void>;

export function SetCollapsedSidebarModules(arg1:Array<string>):Promise<void>;

export function SetConnectionSchemas(arg1:string,arg2:Array<string>):Promise<void>;

export function SetEditorHeight(arg1:number):Promise<void>;

export function SetEditorTheme(arg1:string):Promise<void>;

export function SetOpenTabs(arg1:Array<vault.OpenTabInfo>):Promise<void>;

export function SetRedisHashField(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function SetRedisJSONValue(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetRedisListIndex(arg1:string,arg2:string,arg3:number,arg4:string):Promise<void>;

export function SetRedisStringValue(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetRememberMasterKey(arg1:boolean):Promise<void>;

export function SetSidebarCollapsed(arg1:boolean):Promise<void>;

export function SetSshTerminalTheme(arg1:string):Promise<void>;

export function SetTheme(arg1:string):Promise<void>;

export function SftpHomeDir(arg1:string):Promise<string>;

export function SftpPathPermissions(arg1:string,arg2:string):Promise<sftpx.PermInfo>;

export function StartSftpTransfer(arg1:main.SftpTransferInput):Promise<void>;

export function SyncSchemaMetadata(arg1:string,arg2:string):Promise<db.SchemaMetadata>;

export function TestConnection(arg1:main.ConnectionInput):Promise<void>;

export function TryAutoUnlock():Promise<boolean>;

export function UnlockVault(arg1:string):Promise<void>;

export function UpdateConnection(arg1:string,arg2:main.ConnectionInput,arg3:boolean):Promise<vault.ConnectionSummary>;

export function UpdateSshSnippet(arg1:string,arg2:string,arg3:string):Promise<void>;

export function WriteSSHTerminal(arg1:string,arg2:string):Promise<void>;
