// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function InitializeVault(arg1) {
  return window['go']['main']['App']['InitializeVault'](arg1);
}

export function IsVaultInitialized() {
  return window['go']['main']['App']['IsVaultInitialized']();
}

export function UnlockVault(arg1) {
  return window['go']['main']['App']['UnlockVault'](arg1);
}
