// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BackupVault(arg1) {
  return window['go']['main']['App']['BackupVault'](arg1);
}

export function BeginTransaction(arg1) {
  return window['go']['main']['App']['BeginTransaction'](arg1);
}

export function CancelQuery(arg1) {
  return window['go']['main']['App']['CancelQuery'](arg1);
}

export function ClearRecentFiles() {
  return window['go']['main']['App']['ClearRecentFiles']();
}

export function CommitTransaction(arg1) {
  return window['go']['main']['App']['CommitTransaction'](arg1);
}

export function DeleteConnection(arg1) {
  return window['go']['main']['App']['DeleteConnection'](arg1);
}

export function DisconnectConnection(arg1) {
  return window['go']['main']['App']['DisconnectConnection'](arg1);
}

export function ExecuteQuery(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExecuteQuery'](arg1, arg2, arg3);
}

export function ExplainQuery(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExplainQuery'](arg1, arg2, arg3);
}

export function ExportConnectionConfig(arg1) {
  return window['go']['main']['App']['ExportConnectionConfig'](arg1);
}

export function ExportResult(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExportResult'](arg1, arg2, arg3);
}

export function ExportSchemaDDL(arg1, arg2) {
  return window['go']['main']['App']['ExportSchemaDDL'](arg1, arg2);
}

export function ExportTableDDL(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExportTableDDL'](arg1, arg2, arg3);
}

export function GenerateProjectDocs(arg1, arg2, arg3) {
  return window['go']['main']['App']['GenerateProjectDocs'](arg1, arg2, arg3);
}

export function GetConnectionForEdit(arg1) {
  return window['go']['main']['App']['GetConnectionForEdit'](arg1);
}

export function GetSchemaMetadata(arg1, arg2) {
  return window['go']['main']['App']['GetSchemaMetadata'](arg1, arg2);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function HasOpenTransaction(arg1) {
  return window['go']['main']['App']['HasOpenTransaction'](arg1);
}

export function InitializeVault(arg1) {
  return window['go']['main']['App']['InitializeVault'](arg1);
}

export function IsVaultInitialized() {
  return window['go']['main']['App']['IsVaultInitialized']();
}

export function ListConnections() {
  return window['go']['main']['App']['ListConnections']();
}

export function ListExplainHistory(arg1, arg2) {
  return window['go']['main']['App']['ListExplainHistory'](arg1, arg2);
}

export function ListQueryHistory(arg1, arg2) {
  return window['go']['main']['App']['ListQueryHistory'](arg1, arg2);
}

export function ListRecentFiles() {
  return window['go']['main']['App']['ListRecentFiles']();
}

export function ListSchemas(arg1, arg2) {
  return window['go']['main']['App']['ListSchemas'](arg1, arg2);
}

export function ListSchemasForNewConnection(arg1) {
  return window['go']['main']['App']['ListSchemasForNewConnection'](arg1);
}

export function OpenSQLFileDialog() {
  return window['go']['main']['App']['OpenSQLFileDialog']();
}

export function OpenSQLFilePath(arg1) {
  return window['go']['main']['App']['OpenSQLFilePath'](arg1);
}

export function RegenerateProjectDocs(arg1, arg2, arg3) {
  return window['go']['main']['App']['RegenerateProjectDocs'](arg1, arg2, arg3);
}

export function RestoreVaultBackup(arg1) {
  return window['go']['main']['App']['RestoreVaultBackup'](arg1);
}

export function RollbackTransaction(arg1) {
  return window['go']['main']['App']['RollbackTransaction'](arg1);
}

export function SaveConnection(arg1, arg2) {
  return window['go']['main']['App']['SaveConnection'](arg1, arg2);
}

export function SaveSQLFile(arg1, arg2) {
  return window['go']['main']['App']['SaveSQLFile'](arg1, arg2);
}

export function SaveSQLFileAs(arg1, arg2) {
  return window['go']['main']['App']['SaveSQLFileAs'](arg1, arg2);
}

export function SetConnectionSchemas(arg1, arg2) {
  return window['go']['main']['App']['SetConnectionSchemas'](arg1, arg2);
}

export function SetEditorHeight(arg1) {
  return window['go']['main']['App']['SetEditorHeight'](arg1);
}

export function SetOpenTabs(arg1) {
  return window['go']['main']['App']['SetOpenTabs'](arg1);
}

export function SetSidebarCollapsed(arg1) {
  return window['go']['main']['App']['SetSidebarCollapsed'](arg1);
}

export function SetTheme(arg1) {
  return window['go']['main']['App']['SetTheme'](arg1);
}

export function SyncSchemaMetadata(arg1, arg2) {
  return window['go']['main']['App']['SyncSchemaMetadata'](arg1, arg2);
}

export function TestConnection(arg1) {
  return window['go']['main']['App']['TestConnection'](arg1);
}

export function UnlockVault(arg1) {
  return window['go']['main']['App']['UnlockVault'](arg1);
}

export function UpdateConnection(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateConnection'](arg1, arg2, arg3);
}
