// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActiveConnectionIds() {
  return window['go']['main']['App']['ActiveConnectionIds']();
}

export function AddRedisSetMember(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddRedisSetMember'](arg1, arg2, arg3);
}

export function AddRedisZSetMember(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddRedisZSetMember'](arg1, arg2, arg3, arg4);
}

export function AgentChatHistory(arg1, arg2) {
  return window['go']['main']['App']['AgentChatHistory'](arg1, arg2);
}

export function AgentChatModes(arg1) {
  return window['go']['main']['App']['AgentChatModes'](arg1);
}

export function AgentChatSupported(arg1) {
  return window['go']['main']['App']['AgentChatSupported'](arg1);
}

export function AgentModelCatalog(arg1) {
  return window['go']['main']['App']['AgentModelCatalog'](arg1);
}

export function AgentPlans() {
  return window['go']['main']['App']['AgentPlans']();
}

export function AnalyzeRedisPrefixes(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AnalyzeRedisPrefixes'](arg1, arg2, arg3, arg4);
}

export function AppVersion() {
  return window['go']['main']['App']['AppVersion']();
}

export function AppendSshHistory(arg1, arg2) {
  return window['go']['main']['App']['AppendSshHistory'](arg1, arg2);
}

export function AskAgentOnce(arg1, arg2, arg3) {
  return window['go']['main']['App']['AskAgentOnce'](arg1, arg2, arg3);
}

export function BackupVault(arg1) {
  return window['go']['main']['App']['BackupVault'](arg1);
}

export function BeginRedisTransaction(arg1) {
  return window['go']['main']['App']['BeginRedisTransaction'](arg1);
}

export function BeginTransaction(arg1) {
  return window['go']['main']['App']['BeginTransaction'](arg1);
}

export function CancelAgentChat(arg1) {
  return window['go']['main']['App']['CancelAgentChat'](arg1);
}

export function CancelMongoQuery(arg1) {
  return window['go']['main']['App']['CancelMongoQuery'](arg1);
}

export function CancelQuery(arg1) {
  return window['go']['main']['App']['CancelQuery'](arg1);
}

export function CancelRedisCommand(arg1) {
  return window['go']['main']['App']['CancelRedisCommand'](arg1);
}

export function CancelSftpTransfer(arg1) {
  return window['go']['main']['App']['CancelSftpTransfer'](arg1);
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function CheckRedisLuaScript(arg1, arg2) {
  return window['go']['main']['App']['CheckRedisLuaScript'](arg1, arg2);
}

export function CheckSQLMutation(arg1) {
  return window['go']['main']['App']['CheckSQLMutation'](arg1);
}

export function CheckSftpConflicts(arg1) {
  return window['go']['main']['App']['CheckSftpConflicts'](arg1);
}

export function ChmodSftpPath(arg1, arg2, arg3) {
  return window['go']['main']['App']['ChmodSftpPath'](arg1, arg2, arg3);
}

export function ClearAgentKey(arg1) {
  return window['go']['main']['App']['ClearAgentKey'](arg1);
}

export function ClearAllSshHistory() {
  return window['go']['main']['App']['ClearAllSshHistory']();
}

export function ClearQueryHistory(arg1) {
  return window['go']['main']['App']['ClearQueryHistory'](arg1);
}

export function ClearRecentFiles() {
  return window['go']['main']['App']['ClearRecentFiles']();
}

export function ClearSshHistory(arg1) {
  return window['go']['main']['App']['ClearSshHistory'](arg1);
}

export function CloseLocalTerminal(arg1) {
  return window['go']['main']['App']['CloseLocalTerminal'](arg1);
}

export function CloseSSHTerminal(arg1) {
  return window['go']['main']['App']['CloseSSHTerminal'](arg1);
}

export function CloseSftpBrowse(arg1) {
  return window['go']['main']['App']['CloseSftpBrowse'](arg1);
}

export function CommitTransaction(arg1) {
  return window['go']['main']['App']['CommitTransaction'](arg1);
}

export function CompleteSQL(arg1) {
  return window['go']['main']['App']['CompleteSQL'](arg1);
}

export function ConnectionEnvironment(arg1) {
  return window['go']['main']['App']['ConnectionEnvironment'](arg1);
}

export function CountMongoDocuments(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CountMongoDocuments'](arg1, arg2, arg3, arg4);
}

export function CreateAgentChat(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateAgentChat'](arg1, arg2, arg3, arg4);
}

export function CreateFolder(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateFolder'](arg1, arg2, arg3);
}

export function CreateSshSnippet(arg1, arg2) {
  return window['go']['main']['App']['CreateSshSnippet'](arg1, arg2);
}

export function DefaultShellID() {
  return window['go']['main']['App']['DefaultShellID']();
}

export function DeleteAgentChat(arg1) {
  return window['go']['main']['App']['DeleteAgentChat'](arg1);
}

export function DeleteConnection(arg1) {
  return window['go']['main']['App']['DeleteConnection'](arg1);
}

export function DeleteFolder(arg1) {
  return window['go']['main']['App']['DeleteFolder'](arg1);
}

export function DeleteMongoDocument(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['DeleteMongoDocument'](arg1, arg2, arg3, arg4);
}

export function DeleteQueryHistoryEntry(arg1) {
  return window['go']['main']['App']['DeleteQueryHistoryEntry'](arg1);
}

export function DeleteRedisHashField(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteRedisHashField'](arg1, arg2, arg3);
}

export function DeleteRedisKey(arg1, arg2) {
  return window['go']['main']['App']['DeleteRedisKey'](arg1, arg2);
}

export function DeleteRedisKeys(arg1, arg2) {
  return window['go']['main']['App']['DeleteRedisKeys'](arg1, arg2);
}

export function DeleteSSHKey(arg1) {
  return window['go']['main']['App']['DeleteSSHKey'](arg1);
}

export function DeleteSftpPath(arg1, arg2) {
  return window['go']['main']['App']['DeleteSftpPath'](arg1, arg2);
}

export function DeleteSshSnippet(arg1) {
  return window['go']['main']['App']['DeleteSshSnippet'](arg1);
}

export function DetectSQLiteEncryption(arg1) {
  return window['go']['main']['App']['DetectSQLiteEncryption'](arg1);
}

export function DiscardRedisTransaction(arg1) {
  return window['go']['main']['App']['DiscardRedisTransaction'](arg1);
}

export function DisconnectConnection(arg1) {
  return window['go']['main']['App']['DisconnectConnection'](arg1);
}

export function ExecRedisTransaction(arg1) {
  return window['go']['main']['App']['ExecRedisTransaction'](arg1);
}

export function ExecuteMongoQuery(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ExecuteMongoQuery'](arg1, arg2, arg3, arg4);
}

export function ExecuteQuery(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ExecuteQuery'](arg1, arg2, arg3, arg4);
}

export function ExecuteRedisCommand(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExecuteRedisCommand'](arg1, arg2, arg3);
}

export function ExplainQuery(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExplainQuery'](arg1, arg2, arg3);
}

export function ExportConnectionConfig(arg1) {
  return window['go']['main']['App']['ExportConnectionConfig'](arg1);
}

export function ExportRedisKeys(arg1, arg2) {
  return window['go']['main']['App']['ExportRedisKeys'](arg1, arg2);
}

export function ExportResult(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExportResult'](arg1, arg2, arg3);
}

export function ExportSchemaDDL(arg1, arg2) {
  return window['go']['main']['App']['ExportSchemaDDL'](arg1, arg2);
}

export function ExportTableDDL(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExportTableDDL'](arg1, arg2, arg3);
}

export function FetchMoreRows(arg1) {
  return window['go']['main']['App']['FetchMoreRows'](arg1);
}

export function GenerateProjectDocs(arg1, arg2, arg3) {
  return window['go']['main']['App']['GenerateProjectDocs'](arg1, arg2, arg3);
}

export function GetConnectionForEdit(arg1) {
  return window['go']['main']['App']['GetConnectionForEdit'](arg1);
}

export function GetMongoDefaultDatabase(arg1) {
  return window['go']['main']['App']['GetMongoDefaultDatabase'](arg1);
}

export function GetMongoIndexes(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetMongoIndexes'](arg1, arg2, arg3);
}

export function GetObjectDDL(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['GetObjectDDL'](arg1, arg2, arg3, arg4, arg5);
}

export function GetRedisKeyInfo(arg1, arg2) {
  return window['go']['main']['App']['GetRedisKeyInfo'](arg1, arg2);
}

export function GetRedisKeyValue(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['GetRedisKeyValue'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function GetRedisServerInfo(arg1) {
  return window['go']['main']['App']['GetRedisServerInfo'](arg1);
}

export function GetRedisStats(arg1) {
  return window['go']['main']['App']['GetRedisStats'](arg1);
}

export function GetSchemaIndexStatus(arg1) {
  return window['go']['main']['App']['GetSchemaIndexStatus'](arg1);
}

export function GetSchemaMetadata(arg1, arg2) {
  return window['go']['main']['App']['GetSchemaMetadata'](arg1, arg2);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GitAbort(arg1, arg2) {
  return window['go']['main']['App']['GitAbort'](arg1, arg2);
}

export function GitAddRemote(arg1, arg2, arg3) {
  return window['go']['main']['App']['GitAddRemote'](arg1, arg2, arg3);
}

export function GitAddRepo(arg1) {
  return window['go']['main']['App']['GitAddRepo'](arg1);
}

export function GitAddWorktree(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GitAddWorktree'](arg1, arg2, arg3, arg4);
}

export function GitAgentContext(arg1) {
  return window['go']['main']['App']['GitAgentContext'](arg1);
}

export function GitAgentUsage(arg1, arg2) {
  return window['go']['main']['App']['GitAgentUsage'](arg1, arg2);
}

export function GitApplyPatch(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GitApplyPatch'](arg1, arg2, arg3, arg4);
}

export function GitBlame(arg1, arg2, arg3) {
  return window['go']['main']['App']['GitBlame'](arg1, arg2, arg3);
}

export function GitBranches(arg1, arg2) {
  return window['go']['main']['App']['GitBranches'](arg1, arg2);
}

export function GitChangedFiles(arg1, arg2) {
  return window['go']['main']['App']['GitChangedFiles'](arg1, arg2);
}

export function GitCheckout(arg1, arg2) {
  return window['go']['main']['App']['GitCheckout'](arg1, arg2);
}

export function GitCherryPick(arg1, arg2, arg3) {
  return window['go']['main']['App']['GitCherryPick'](arg1, arg2, arg3);
}

export function GitClearCommandLog() {
  return window['go']['main']['App']['GitClearCommandLog']();
}

export function GitCloneRepo(arg1, arg2, arg3) {
  return window['go']['main']['App']['GitCloneRepo'](arg1, arg2, arg3);
}

export function GitCommandLog() {
  return window['go']['main']['App']['GitCommandLog']();
}

export function GitCommit(arg1, arg2, arg3) {
  return window['go']['main']['App']['GitCommit'](arg1, arg2, arg3);
}

export function GitConflictedFiles(arg1) {
  return window['go']['main']['App']['GitConflictedFiles'](arg1);
}

export function GitContinue(arg1, arg2) {
  return window['go']['main']['App']['GitContinue'](arg1, arg2);
}

export function GitCreateBranch(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GitCreateBranch'](arg1, arg2, arg3, arg4);
}

export function GitCreateTag(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GitCreateTag'](arg1, arg2, arg3, arg4);
}

export function GitDeleteBranch(arg1, arg2, arg3) {
  return window['go']['main']['App']['GitDeleteBranch'](arg1, arg2, arg3);
}

export function GitDeleteCredential(arg1) {
  return window['go']['main']['App']['GitDeleteCredential'](arg1);
}

export function GitDeleteRemoteBranch(arg1, arg2, arg3) {
  return window['go']['main']['App']['GitDeleteRemoteBranch'](arg1, arg2, arg3);
}

export function GitDeleteRemoteTag(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GitDeleteRemoteTag'](arg1, arg2, arg3, arg4);
}

export function GitDeleteTag(arg1, arg2) {
  return window['go']['main']['App']['GitDeleteTag'](arg1, arg2);
}

export function GitDiff(arg1, arg2) {
  return window['go']['main']['App']['GitDiff'](arg1, arg2);
}

export function GitDiscard(arg1, arg2) {
  return window['go']['main']['App']['GitDiscard'](arg1, arg2);
}

export function GitFetch(arg1, arg2, arg3) {
  return window['go']['main']['App']['GitFetch'](arg1, arg2, arg3);
}

export function GitFileAtCommit(arg1, arg2, arg3) {
  return window['go']['main']['App']['GitFileAtCommit'](arg1, arg2, arg3);
}

export function GitForgeInfo(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GitForgeInfo'](arg1, arg2, arg3, arg4);
}

export function GitIdentity(arg1) {
  return window['go']['main']['App']['GitIdentity'](arg1);
}

export function GitInProgress(arg1) {
  return window['go']['main']['App']['GitInProgress'](arg1);
}

export function GitInitRepo(arg1) {
  return window['go']['main']['App']['GitInitRepo'](arg1);
}

export function GitListCredentials() {
  return window['go']['main']['App']['GitListCredentials']();
}

export function GitListRepos() {
  return window['go']['main']['App']['GitListRepos']();
}

export function GitListWorkTree(arg1) {
  return window['go']['main']['App']['GitListWorkTree'](arg1);
}

export function GitLog(arg1, arg2) {
  return window['go']['main']['App']['GitLog'](arg1, arg2);
}

export function GitMCPConfig(arg1) {
  return window['go']['main']['App']['GitMCPConfig'](arg1);
}

export function GitMerge(arg1, arg2, arg3) {
  return window['go']['main']['App']['GitMerge'](arg1, arg2, arg3);
}

export function GitMoveRepoToFolder(arg1, arg2) {
  return window['go']['main']['App']['GitMoveRepoToFolder'](arg1, arg2);
}

export function GitOpenInBrowser(arg1) {
  return window['go']['main']['App']['GitOpenInBrowser'](arg1);
}

export function GitPickFolder(arg1) {
  return window['go']['main']['App']['GitPickFolder'](arg1);
}

export function GitPickRepoFolder() {
  return window['go']['main']['App']['GitPickRepoFolder']();
}

export function GitProbe() {
  return window['go']['main']['App']['GitProbe']();
}

export function GitPruneWorktrees(arg1) {
  return window['go']['main']['App']['GitPruneWorktrees'](arg1);
}

export function GitPull(arg1, arg2, arg3) {
  return window['go']['main']['App']['GitPull'](arg1, arg2, arg3);
}

export function GitPush(arg1, arg2, arg3) {
  return window['go']['main']['App']['GitPush'](arg1, arg2, arg3);
}

export function GitPushTag(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GitPushTag'](arg1, arg2, arg3, arg4);
}

export function GitReadConflictFile(arg1, arg2) {
  return window['go']['main']['App']['GitReadConflictFile'](arg1, arg2);
}

export function GitReadWorkFile(arg1, arg2) {
  return window['go']['main']['App']['GitReadWorkFile'](arg1, arg2);
}

export function GitRebaseApply(arg1, arg2, arg3) {
  return window['go']['main']['App']['GitRebaseApply'](arg1, arg2, arg3);
}

export function GitRebaseTodo(arg1, arg2) {
  return window['go']['main']['App']['GitRebaseTodo'](arg1, arg2);
}

export function GitRefreshProbe() {
  return window['go']['main']['App']['GitRefreshProbe']();
}

export function GitRemoteURLForCopy(arg1, arg2) {
  return window['go']['main']['App']['GitRemoteURLForCopy'](arg1, arg2);
}

export function GitRemotes(arg1) {
  return window['go']['main']['App']['GitRemotes'](arg1);
}

export function GitRemoveMCPServer(arg1, arg2) {
  return window['go']['main']['App']['GitRemoveMCPServer'](arg1, arg2);
}

export function GitRemoveRemote(arg1, arg2) {
  return window['go']['main']['App']['GitRemoveRemote'](arg1, arg2);
}

export function GitRemoveRepo(arg1) {
  return window['go']['main']['App']['GitRemoveRepo'](arg1);
}

export function GitRemoveWorktree(arg1, arg2, arg3) {
  return window['go']['main']['App']['GitRemoveWorktree'](arg1, arg2, arg3);
}

export function GitRenameBranch(arg1, arg2, arg3) {
  return window['go']['main']['App']['GitRenameBranch'](arg1, arg2, arg3);
}

export function GitRenameRemote(arg1, arg2, arg3) {
  return window['go']['main']['App']['GitRenameRemote'](arg1, arg2, arg3);
}

export function GitRenameRepo(arg1, arg2) {
  return window['go']['main']['App']['GitRenameRepo'](arg1, arg2);
}

export function GitRepoWorkspace(arg1) {
  return window['go']['main']['App']['GitRepoWorkspace'](arg1);
}

export function GitReset(arg1, arg2, arg3) {
  return window['go']['main']['App']['GitReset'](arg1, arg2, arg3);
}

export function GitResolveConflictFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['GitResolveConflictFile'](arg1, arg2, arg3);
}

export function GitRevert(arg1, arg2, arg3) {
  return window['go']['main']['App']['GitRevert'](arg1, arg2, arg3);
}

export function GitSaveCredential(arg1, arg2, arg3) {
  return window['go']['main']['App']['GitSaveCredential'](arg1, arg2, arg3);
}

export function GitSetDefaultAgent(arg1, arg2) {
  return window['go']['main']['App']['GitSetDefaultAgent'](arg1, arg2);
}

export function GitSetDiffPrefs(arg1, arg2, arg3) {
  return window['go']['main']['App']['GitSetDiffPrefs'](arg1, arg2, arg3);
}

export function GitSetIdentity(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GitSetIdentity'](arg1, arg2, arg3, arg4);
}

export function GitSetOpenFiles(arg1, arg2) {
  return window['go']['main']['App']['GitSetOpenFiles'](arg1, arg2);
}

export function GitSetPaneWidths(arg1, arg2) {
  return window['go']['main']['App']['GitSetPaneWidths'](arg1, arg2);
}

export function GitSetPinnedBranches(arg1, arg2) {
  return window['go']['main']['App']['GitSetPinnedBranches'](arg1, arg2);
}

export function GitSetRemoteURL(arg1, arg2, arg3) {
  return window['go']['main']['App']['GitSetRemoteURL'](arg1, arg2, arg3);
}

export function GitSetUpstream(arg1, arg2, arg3) {
  return window['go']['main']['App']['GitSetUpstream'](arg1, arg2, arg3);
}

export function GitStage(arg1, arg2) {
  return window['go']['main']['App']['GitStage'](arg1, arg2);
}

export function GitStageAll(arg1) {
  return window['go']['main']['App']['GitStageAll'](arg1);
}

export function GitStashApply(arg1, arg2, arg3) {
  return window['go']['main']['App']['GitStashApply'](arg1, arg2, arg3);
}

export function GitStashDiff(arg1, arg2) {
  return window['go']['main']['App']['GitStashDiff'](arg1, arg2);
}

export function GitStashDrop(arg1, arg2) {
  return window['go']['main']['App']['GitStashDrop'](arg1, arg2);
}

export function GitStashPush(arg1, arg2, arg3) {
  return window['go']['main']['App']['GitStashPush'](arg1, arg2, arg3);
}

export function GitStashes(arg1) {
  return window['go']['main']['App']['GitStashes'](arg1);
}

export function GitStatus(arg1) {
  return window['go']['main']['App']['GitStatus'](arg1);
}

export function GitTags(arg1) {
  return window['go']['main']['App']['GitTags'](arg1);
}

export function GitUnsetUpstream(arg1, arg2) {
  return window['go']['main']['App']['GitUnsetUpstream'](arg1, arg2);
}

export function GitUnstage(arg1, arg2) {
  return window['go']['main']['App']['GitUnstage'](arg1, arg2);
}

export function GitUpsertMCPServer(arg1, arg2) {
  return window['go']['main']['App']['GitUpsertMCPServer'](arg1, arg2);
}

export function GitWorktrees(arg1) {
  return window['go']['main']['App']['GitWorktrees'](arg1);
}

export function GitWriteWorkFile(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GitWriteWorkFile'](arg1, arg2, arg3, arg4);
}

export function HasOpenTransaction(arg1) {
  return window['go']['main']['App']['HasOpenTransaction'](arg1);
}

export function InitializeVault(arg1) {
  return window['go']['main']['App']['InitializeVault'](arg1);
}

export function IsVaultInitialized() {
  return window['go']['main']['App']['IsVaultInitialized']();
}

export function ListAgentChats(arg1) {
  return window['go']['main']['App']['ListAgentChats'](arg1);
}

export function ListAgents() {
  return window['go']['main']['App']['ListAgents']();
}

export function ListConnections() {
  return window['go']['main']['App']['ListConnections']();
}

export function ListExplainHistory(arg1, arg2) {
  return window['go']['main']['App']['ListExplainHistory'](arg1, arg2);
}

export function ListFolders() {
  return window['go']['main']['App']['ListFolders']();
}

export function ListMongoCollections(arg1, arg2, arg3) {
  return window['go']['main']['App']['ListMongoCollections'](arg1, arg2, arg3);
}

export function ListMongoDatabases(arg1) {
  return window['go']['main']['App']['ListMongoDatabases'](arg1);
}

export function ListMongoDocuments(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['ListMongoDocuments'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function ListQueryHistory(arg1, arg2) {
  return window['go']['main']['App']['ListQueryHistory'](arg1, arg2);
}

export function ListRecentFiles() {
  return window['go']['main']['App']['ListRecentFiles']();
}

export function ListRedisKeys(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ListRedisKeys'](arg1, arg2, arg3, arg4, arg5);
}

export function ListSSHKeys() {
  return window['go']['main']['App']['ListSSHKeys']();
}

export function ListSchemas(arg1, arg2) {
  return window['go']['main']['App']['ListSchemas'](arg1, arg2);
}

export function ListSchemasForNewConnection(arg1) {
  return window['go']['main']['App']['ListSchemasForNewConnection'](arg1);
}

export function ListSftpDir(arg1, arg2) {
  return window['go']['main']['App']['ListSftpDir'](arg1, arg2);
}

export function ListShells() {
  return window['go']['main']['App']['ListShells']();
}

export function ListSshHistory(arg1, arg2) {
  return window['go']['main']['App']['ListSshHistory'](arg1, arg2);
}

export function ListSshSnippets() {
  return window['go']['main']['App']['ListSshSnippets']();
}

export function LocalShellLabel(arg1) {
  return window['go']['main']['App']['LocalShellLabel'](arg1);
}

export function MakeSftpDir(arg1, arg2) {
  return window['go']['main']['App']['MakeSftpDir'](arg1, arg2);
}

export function MoveConnectionToFolder(arg1, arg2) {
  return window['go']['main']['App']['MoveConnectionToFolder'](arg1, arg2);
}

export function MoveFolder(arg1, arg2) {
  return window['go']['main']['App']['MoveFolder'](arg1, arg2);
}

export function MoveSshSnippetToFolder(arg1, arg2) {
  return window['go']['main']['App']['MoveSshSnippetToFolder'](arg1, arg2);
}

export function OpenAgentSession(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['OpenAgentSession'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function OpenLocalTerminal(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['OpenLocalTerminal'](arg1, arg2, arg3, arg4);
}

export function OpenLocalTerminalAt(arg1, arg2, arg3) {
  return window['go']['main']['App']['OpenLocalTerminalAt'](arg1, arg2, arg3);
}

export function OpenSQLFileDialog() {
  return window['go']['main']['App']['OpenSQLFileDialog']();
}

export function OpenSQLFilePath(arg1) {
  return window['go']['main']['App']['OpenSQLFilePath'](arg1);
}

export function OpenSSHTerminal(arg1, arg2, arg3) {
  return window['go']['main']['App']['OpenSSHTerminal'](arg1, arg2, arg3);
}

export function OpenSftpBrowse(arg1, arg2) {
  return window['go']['main']['App']['OpenSftpBrowse'](arg1, arg2);
}

export function PersistRedisKey(arg1, arg2) {
  return window['go']['main']['App']['PersistRedisKey'](arg1, arg2);
}

export function PickAutoBackupFolder() {
  return window['go']['main']['App']['PickAutoBackupFolder']();
}

export function PickSQLiteFile() {
  return window['go']['main']['App']['PickSQLiteFile']();
}

export function PickVaultBackupFile(arg1) {
  return window['go']['main']['App']['PickVaultBackupFile'](arg1);
}

export function PickVaultBackupFileFirstRun() {
  return window['go']['main']['App']['PickVaultBackupFileFirstRun']();
}

export function PrimeSchemaIndex(arg1) {
  return window['go']['main']['App']['PrimeSchemaIndex'](arg1);
}

export function PushRedisListValue(arg1, arg2, arg3) {
  return window['go']['main']['App']['PushRedisListValue'](arg1, arg2, arg3);
}

export function ReadRedisStream(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ReadRedisStream'](arg1, arg2, arg3, arg4);
}

export function ReadSftpFileForEdit(arg1, arg2) {
  return window['go']['main']['App']['ReadSftpFileForEdit'](arg1, arg2);
}

export function RecordCompletionUse(arg1, arg2, arg3) {
  return window['go']['main']['App']['RecordCompletionUse'](arg1, arg2, arg3);
}

export function RedisTransactionStatus(arg1) {
  return window['go']['main']['App']['RedisTransactionStatus'](arg1);
}

export function RegenerateProjectDocs(arg1, arg2, arg3) {
  return window['go']['main']['App']['RegenerateProjectDocs'](arg1, arg2, arg3);
}

export function ReleasePagedResult(arg1) {
  return window['go']['main']['App']['ReleasePagedResult'](arg1);
}

export function RemoveRedisListIndex(arg1, arg2, arg3) {
  return window['go']['main']['App']['RemoveRedisListIndex'](arg1, arg2, arg3);
}

export function RemoveRedisSetMember(arg1, arg2, arg3) {
  return window['go']['main']['App']['RemoveRedisSetMember'](arg1, arg2, arg3);
}

export function RemoveRedisZSetMember(arg1, arg2, arg3) {
  return window['go']['main']['App']['RemoveRedisZSetMember'](arg1, arg2, arg3);
}

export function RenameAgentChat(arg1, arg2) {
  return window['go']['main']['App']['RenameAgentChat'](arg1, arg2);
}

export function RenameFolder(arg1, arg2) {
  return window['go']['main']['App']['RenameFolder'](arg1, arg2);
}

export function RenameSSHKey(arg1, arg2) {
  return window['go']['main']['App']['RenameSSHKey'](arg1, arg2);
}

export function RenameSftpPath(arg1, arg2, arg3) {
  return window['go']['main']['App']['RenameSftpPath'](arg1, arg2, arg3);
}

export function ReorderFolder(arg1, arg2) {
  return window['go']['main']['App']['ReorderFolder'](arg1, arg2);
}

export function ReplaceMongoDocument(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ReplaceMongoDocument'](arg1, arg2, arg3, arg4);
}

export function ResetAgentChat(arg1) {
  return window['go']['main']['App']['ResetAgentChat'](arg1);
}

export function ResizeLocalTerminal(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeLocalTerminal'](arg1, arg2, arg3);
}

export function ResizeSSHTerminal(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeSSHTerminal'](arg1, arg2, arg3);
}

export function ResolveJoinCondition(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ResolveJoinCondition'](arg1, arg2, arg3, arg4, arg5);
}

export function RespondAgentApproval(arg1, arg2, arg3) {
  return window['go']['main']['App']['RespondAgentApproval'](arg1, arg2, arg3);
}

export function RestoreVaultBackupFirstRun(arg1, arg2) {
  return window['go']['main']['App']['RestoreVaultBackupFirstRun'](arg1, arg2);
}

export function RestoreVaultBackupFromFile(arg1, arg2) {
  return window['go']['main']['App']['RestoreVaultBackupFromFile'](arg1, arg2);
}

export function ResumeAgentChat(arg1, arg2) {
  return window['go']['main']['App']['ResumeAgentChat'](arg1, arg2);
}

export function RevealConnectionPassword(arg1, arg2) {
  return window['go']['main']['App']['RevealConnectionPassword'](arg1, arg2);
}

export function RollbackTransaction(arg1) {
  return window['go']['main']['App']['RollbackTransaction'](arg1);
}

export function RunRedisLuaScript(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RunRedisLuaScript'](arg1, arg2, arg3, arg4);
}

export function SSHKeyUsage(arg1) {
  return window['go']['main']['App']['SSHKeyUsage'](arg1);
}

export function SampleMongoFields(arg1, arg2, arg3) {
  return window['go']['main']['App']['SampleMongoFields'](arg1, arg2, arg3);
}

export function SaveChatAttachment(arg1, arg2) {
  return window['go']['main']['App']['SaveChatAttachment'](arg1, arg2);
}

export function SaveConnection(arg1, arg2) {
  return window['go']['main']['App']['SaveConnection'](arg1, arg2);
}

export function SaveDDLToFile(arg1, arg2) {
  return window['go']['main']['App']['SaveDDLToFile'](arg1, arg2);
}

export function SaveSQLFile(arg1, arg2) {
  return window['go']['main']['App']['SaveSQLFile'](arg1, arg2);
}

export function SaveSQLFileAs(arg1, arg2) {
  return window['go']['main']['App']['SaveSQLFileAs'](arg1, arg2);
}

export function SaveSSHKey(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveSSHKey'](arg1, arg2, arg3);
}

export function SendAgentChat(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['SendAgentChat'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function SetAgentChatSettings(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetAgentChatSettings'](arg1, arg2, arg3, arg4);
}

export function SetAgentCommand(arg1, arg2) {
  return window['go']['main']['App']['SetAgentCommand'](arg1, arg2);
}

export function SetAgentKey(arg1, arg2) {
  return window['go']['main']['App']['SetAgentKey'](arg1, arg2);
}

export function SetAutoBackupEnabled(arg1) {
  return window['go']['main']['App']['SetAutoBackupEnabled'](arg1);
}

export function SetAutoBackupIntervalHours(arg1) {
  return window['go']['main']['App']['SetAutoBackupIntervalHours'](arg1);
}

export function SetAutoSaveEnabled(arg1) {
  return window['go']['main']['App']['SetAutoSaveEnabled'](arg1);
}

export function SetAutoSaveIntervalSeconds(arg1) {
  return window['go']['main']['App']['SetAutoSaveIntervalSeconds'](arg1);
}

export function SetCollapsedSidebarModules(arg1) {
  return window['go']['main']['App']['SetCollapsedSidebarModules'](arg1);
}

export function SetConnectionSchemas(arg1, arg2) {
  return window['go']['main']['App']['SetConnectionSchemas'](arg1, arg2);
}

export function SetEditorHeight(arg1) {
  return window['go']['main']['App']['SetEditorHeight'](arg1);
}

export function SetEditorTheme(arg1) {
  return window['go']['main']['App']['SetEditorTheme'](arg1);
}

export function SetGitLayout(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SetGitLayout'](arg1, arg2, arg3, arg4, arg5);
}

export function SetGitPanelSessions(arg1) {
  return window['go']['main']['App']['SetGitPanelSessions'](arg1);
}

export function SetLocalShell(arg1) {
  return window['go']['main']['App']['SetLocalShell'](arg1);
}

export function SetOpenTabs(arg1) {
  return window['go']['main']['App']['SetOpenTabs'](arg1);
}

export function SetQueryPageSize(arg1) {
  return window['go']['main']['App']['SetQueryPageSize'](arg1);
}

export function SetRedisHashField(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetRedisHashField'](arg1, arg2, arg3, arg4);
}

export function SetRedisJSONValue(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetRedisJSONValue'](arg1, arg2, arg3);
}

export function SetRedisKeyTTL(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetRedisKeyTTL'](arg1, arg2, arg3);
}

export function SetRedisListIndex(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetRedisListIndex'](arg1, arg2, arg3, arg4);
}

export function SetRedisStringValue(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetRedisStringValue'](arg1, arg2, arg3);
}

export function SetRememberMasterKey(arg1) {
  return window['go']['main']['App']['SetRememberMasterKey'](arg1);
}

export function SetSidebarCollapsed(arg1) {
  return window['go']['main']['App']['SetSidebarCollapsed'](arg1);
}

export function SetSshHistoryEnabled(arg1) {
  return window['go']['main']['App']['SetSshHistoryEnabled'](arg1);
}

export function SetSshTerminalTheme(arg1) {
  return window['go']['main']['App']['SetSshTerminalTheme'](arg1);
}

export function SetTerminalFontSize(arg1) {
  return window['go']['main']['App']['SetTerminalFontSize'](arg1);
}

export function SetTheme(arg1) {
  return window['go']['main']['App']['SetTheme'](arg1);
}

export function SftpHomeDir(arg1) {
  return window['go']['main']['App']['SftpHomeDir'](arg1);
}

export function SftpPathPermissions(arg1, arg2) {
  return window['go']['main']['App']['SftpPathPermissions'](arg1, arg2);
}

export function SshHistoryEnabled() {
  return window['go']['main']['App']['SshHistoryEnabled']();
}

export function StartSftpTransfer(arg1) {
  return window['go']['main']['App']['StartSftpTransfer'](arg1);
}

export function StopRedisMonitor(arg1) {
  return window['go']['main']['App']['StopRedisMonitor'](arg1);
}

export function SubscribeRedisChannels(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SubscribeRedisChannels'](arg1, arg2, arg3, arg4);
}

export function SuggestInlineSQL(arg1) {
  return window['go']['main']['App']['SuggestInlineSQL'](arg1);
}

export function SyncSchemaMetadata(arg1, arg2) {
  return window['go']['main']['App']['SyncSchemaMetadata'](arg1, arg2);
}

export function TestConnection(arg1) {
  return window['go']['main']['App']['TestConnection'](arg1);
}

export function TouchAgentChat(arg1, arg2) {
  return window['go']['main']['App']['TouchAgentChat'](arg1, arg2);
}

export function TryAutoUnlock() {
  return window['go']['main']['App']['TryAutoUnlock']();
}

export function UnlockVault(arg1) {
  return window['go']['main']['App']['UnlockVault'](arg1);
}

export function UpdateConnection(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateConnection'](arg1, arg2, arg3);
}

export function UpdateSshSnippet(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateSshSnippet'](arg1, arg2, arg3);
}

export function WriteLocalTerminal(arg1, arg2) {
  return window['go']['main']['App']['WriteLocalTerminal'](arg1, arg2);
}

export function WriteSSHTerminal(arg1, arg2) {
  return window['go']['main']['App']['WriteSSHTerminal'](arg1, arg2);
}

export function WriteSftpFileFromEdit(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['WriteSftpFileFromEdit'](arg1, arg2, arg3, arg4);
}
