// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {agentchat} from '../models';
import {agentmodels} from '../models';
import {agentplan} from '../models';
import {agentctx} from '../models';
import {db} from '../models';
import {updatecheck} from '../models';
import {redisquery} from '../models';
import {sftpx} from '../models';
import {sqlintel} from '../models';
import {vault} from '../models';
import {explain} from '../models';
import {agentusage} from '../models';
import {git} from '../models';
import {mcpconf} from '../models';
import {agents} from '../models';
import {localterm} from '../models';
import {mcpserver} from '../models';

export function ActiveConnectionIds():Promise<Array<string>>;

export function AddRedisSetMember(arg1:string,arg2:string,arg3:string):Promise<void>;

export function AddRedisZSetMember(arg1:string,arg2:string,arg3:string,arg4:number):Promise<void>;

export function AgentActive():Promise<main.ActiveAgent>;

export function AgentAnalyzePlan(arg1:string):Promise<string>;

export function AgentAsk(arg1:string,arg2:string,arg3:string):Promise<string>;

export function AgentCLIConversations(arg1:string,arg2:string):Promise<Array<agentchat.Conversation>>;

export function AgentChatHistory(arg1:string,arg2:string):Promise<Array<agentchat.PastTurn>>;

export function AgentChatModes(arg1:string):Promise<Array<string>>;

export function AgentChatSupported(arg1:string):Promise<boolean>;

export function AgentFixSQL(arg1:string,arg2:string,arg3:string):Promise<main.SQLSuggestion>;

export function AgentGenerateSQL(arg1:string,arg2:string,arg3:string):Promise<main.SQLSuggestion>;

export function AgentModelCatalog(arg1:string):Promise<agentmodels.Catalog>;

export function AgentPlans():Promise<Array<agentplan.Plan>>;

export function AgentRefPolicies():Promise<Array<agentctx.Policy>>;

export function AgentResolveRefs(arg1:string,arg2:string,arg3:string):Promise<Array<agentctx.Resolved>>;

export function AnalyzeRedisPrefixes(arg1:string,arg2:string,arg3:number,arg4:boolean):Promise<db.RedisPrefixReport>;

export function AnalyzeSSHError(arg1:string,arg2:string,arg3:number):Promise<main.SSHErrorAnalysis>;

export function AppVersion():Promise<string>;

export function AppendSshHistory(arg1:string,arg2:string):Promise<boolean>;

export function AskAgentOnce(arg1:string,arg2:string,arg3:string):Promise<string>;

export function BackupVault(arg1:string):Promise<string>;

export function BeginRedisTransaction(arg1:string):Promise<void>;

export function BeginTransaction(arg1:string):Promise<void>;

export function CallTool(arg1:string,arg2:Record<string, any>):Promise<string>;

export function CancelAgentChat(arg1:string):Promise<void>;

export function CancelMongoQuery(arg1:string):Promise<void>;

export function CancelQuery(arg1:string):Promise<void>;

export function CancelRedisCommand(arg1:string):Promise<void>;

export function CancelSftpTransfer(arg1:string):Promise<void>;

export function CheckForUpdate():Promise<updatecheck.Info>;

export function CheckRedisLuaScript(arg1:string,arg2:string):Promise<redisquery.LuaResult>;

export function CheckSQLMutation(arg1:string):Promise<boolean>;

export function CheckSftpConflicts(arg1:main.SftpTransferInput):Promise<Array<sftpx.Conflict>>;

export function ChmodSftpPath(arg1:string,arg2:string,arg3:number):Promise<void>;

export function ClearAgentKey(arg1:string):Promise<void>;

export function ClearAllSshHistory():Promise<number>;

export function ClearQueryHistory(arg1:string):Promise<void>;

export function ClearRecentFiles():Promise<void>;

export function ClearSshHistory(arg1:string):Promise<number>;

export function CloseLocalTerminal(arg1:string):Promise<void>;

export function CloseSSHTerminal(arg1:string):Promise<void>;

export function CloseSftpBrowse(arg1:string):Promise<void>;

export function CommitTransaction(arg1:string):Promise<void>;

export function CompleteSQL(arg1:sqlintel.Request):Promise<sqlintel.Response>;

export function ConnectionEnvironment(arg1:string):Promise<string>;

export function CountMongoDocuments(arg1:string,arg2:string,arg3:string,arg4:string):Promise<number>;

export function CreateAgentChat(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<void>;

export function CreateFolder(arg1:string,arg2:string,arg3:string):Promise<vault.Folder>;

export function CreateNote(arg1:string,arg2:string):Promise<string>;

export function CreateSshSnippet(arg1:string,arg2:string):Promise<vault.SshSnippet>;

export function DefaultShellID():Promise<string>;

export function DeleteAgentChat(arg1:string):Promise<void>;

export function DeleteConnection(arg1:string):Promise<void>;

export function DeleteFolder(arg1:string):Promise<void>;

export function DeleteMongoDocument(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function DeleteNote(arg1:string):Promise<void>;

export function DeleteQueryHistoryEntry(arg1:string):Promise<void>;

export function DeleteRedisHashField(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DeleteRedisKey(arg1:string,arg2:string):Promise<void>;

export function DeleteRedisKeys(arg1:string,arg2:Array<string>):Promise<number>;

export function DeleteSSHKey(arg1:string):Promise<void>;

export function DeleteSftpPath(arg1:string,arg2:string):Promise<void>;

export function DeleteSshSnippet(arg1:string):Promise<void>;

export function DetectSQLiteEncryption(arg1:string):Promise<boolean>;

export function DiscardRedisTransaction(arg1:string):Promise<void>;

export function DisconnectConnection(arg1:string):Promise<void>;

export function ExecRedisTransaction(arg1:string):Promise<any>;

export function ExecuteMongoQuery(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function ExecuteQuery(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<void>;

export function ExecuteRedisCommand(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ExplainQuery(arg1:string,arg2:string,arg3:boolean):Promise<explain.Plan>;

export function ExportConnectionConfig(arg1:string):Promise<string>;

export function ExportRedisKeys(arg1:string,arg2:Array<string>):Promise<Array<db.RedisKeyExport>>;

export function ExportResult(arg1:Array<string>,arg2:Array<any>,arg3:string):Promise<string>;

export function ExportSchemaDDL(arg1:string,arg2:string):Promise<string>;

export function ExportTableDDL(arg1:string,arg2:string,arg3:string):Promise<string>;

export function FetchMoreRows(arg1:string):Promise<void>;

export function GenerateProjectDocs(arg1:string,arg2:string,arg3:string):Promise<boolean>;

export function GetConnectionForEdit(arg1:string):Promise<main.ConnectionEditInfo>;

export function GetMongoDefaultDatabase(arg1:string):Promise<string>;

export function GetMongoIndexes(arg1:string,arg2:string,arg3:string):Promise<Array<db.MongoIndex>>;

export function GetNote(arg1:string):Promise<vault.Note>;

export function GetNoteImage(arg1:string):Promise<vault.NoteAsset>;

export function GetObjectDDL(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number):Promise<string>;

export function GetRedisKeyInfo(arg1:string,arg2:string):Promise<db.RedisKeyInfo>;

export function GetRedisKeyValue(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number,arg6:number):Promise<db.RedisValue>;

export function GetRedisServerInfo(arg1:string):Promise<db.RedisServerInfo>;

export function GetRedisStats(arg1:string):Promise<db.RedisStats>;

export function GetSchemaIndexStatus(arg1:string):Promise<sqlintel.Status>;

export function GetSchemaMetadata(arg1:string,arg2:boolean):Promise<db.SchemaMetadata>;

export function GetSettings():Promise<vault.Settings>;

export function GitAbort(arg1:string,arg2:string):Promise<void>;

export function GitAddRemote(arg1:string,arg2:string,arg3:string):Promise<void>;

export function GitAddRepo(arg1:string):Promise<vault.GitRepo>;

export function GitAddWorktree(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<void>;

export function GitAgentContext(arg1:string):Promise<agentctx.Context>;

export function GitAgentUsage(arg1:string,arg2:number):Promise<agentusage.Usage>;

export function GitApplyPatch(arg1:string,arg2:string,arg3:boolean,arg4:boolean):Promise<void>;

export function GitBlame(arg1:string,arg2:string,arg3:string):Promise<Array<git.BlameLine>>;

export function GitBranches(arg1:string,arg2:boolean):Promise<Array<git.Branch>>;

export function GitChangedFiles(arg1:string,arg2:string):Promise<Array<git.FileDiff>>;

export function GitCheckout(arg1:string,arg2:string):Promise<void>;

export function GitCherryPick(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function GitClearCommandLog():Promise<void>;

export function GitCloneRepo(arg1:string,arg2:string,arg3:git.AuthConfig):Promise<vault.GitRepo>;

export function GitCommandLog():Promise<Array<git.CommandEntry>>;

export function GitCommit(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function GitConflictedFiles(arg1:string):Promise<Array<string>>;

export function GitContinue(arg1:string,arg2:string):Promise<void>;

export function GitCreateBranch(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<void>;

export function GitCreateTag(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function GitDeleteBranch(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function GitDeleteCredential(arg1:string):Promise<void>;

export function GitDeleteRemoteBranch(arg1:string,arg2:string,arg3:git.AuthConfig):Promise<string>;

export function GitDeleteRemoteTag(arg1:string,arg2:string,arg3:string,arg4:git.AuthConfig):Promise<string>;

export function GitDeleteTag(arg1:string,arg2:string):Promise<void>;

export function GitDiff(arg1:string,arg2:git.DiffTarget):Promise<git.FileDiff>;

export function GitDiscard(arg1:string,arg2:Array<string>):Promise<void>;

export function GitFetch(arg1:string,arg2:git.FetchOptions,arg3:git.AuthConfig):Promise<string>;

export function GitFileAtCommit(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GitForgeInfo(arg1:string,arg2:string,arg3:string,arg4:string):Promise<git.ForgeInfo>;

export function GitIdentity(arg1:string):Promise<git.Identity>;

export function GitInProgress(arg1:string):Promise<string>;

export function GitInitRepo(arg1:string):Promise<vault.GitRepo>;

export function GitListCredentials():Promise<Array<vault.GitCredential>>;

export function GitListRepos():Promise<Array<vault.GitRepo>>;

export function GitListWorkTree(arg1:string):Promise<git.WorkTree>;

export function GitLog(arg1:string,arg2:git.LogOptions):Promise<Array<git.CommitInfo>>;

export function GitMCPConfig(arg1:string):Promise<mcpconf.Config>;

export function GitMerge(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function GitMoveRepoToFolder(arg1:string,arg2:string):Promise<void>;

export function GitOpenInBrowser(arg1:string):Promise<void>;

export function GitPickFolder(arg1:string):Promise<string>;

export function GitPickRepoFolder():Promise<string>;

export function GitProbe():Promise<git.Availability>;

export function GitPruneWorktrees(arg1:string):Promise<void>;

export function GitPull(arg1:string,arg2:git.PullOptions,arg3:git.AuthConfig):Promise<string>;

export function GitPush(arg1:string,arg2:git.PushOptions,arg3:git.AuthConfig):Promise<string>;

export function GitPushTag(arg1:string,arg2:string,arg3:string,arg4:git.AuthConfig):Promise<string>;

export function GitReadConflictFile(arg1:string,arg2:string):Promise<string>;

export function GitReadWorkFile(arg1:string,arg2:string):Promise<git.WorkFile>;

export function GitRebaseApply(arg1:string,arg2:string,arg3:Array<git.RebaseAction>):Promise<void>;

export function GitRebaseTodo(arg1:string,arg2:string):Promise<Array<git.RebaseAction>>;

export function GitRefreshProbe():Promise<git.Availability>;

export function GitRemoteURLForCopy(arg1:string,arg2:string):Promise<string>;

export function GitRemotes(arg1:string):Promise<Array<git.Remote>>;

export function GitRemoveMCPServer(arg1:string,arg2:string):Promise<void>;

export function GitRemoveRemote(arg1:string,arg2:string):Promise<void>;

export function GitRemoveRepo(arg1:string):Promise<void>;

export function GitRemoveWorktree(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function GitRenameBranch(arg1:string,arg2:string,arg3:string):Promise<void>;

export function GitRenameRemote(arg1:string,arg2:string,arg3:string):Promise<void>;

export function GitRenameRepo(arg1:string,arg2:string):Promise<void>;

export function GitRepoWorkspace(arg1:string):Promise<vault.GitRepoWorkspace>;

export function GitReset(arg1:string,arg2:string,arg3:string):Promise<void>;

export function GitResolveConflictFile(arg1:string,arg2:string,arg3:string):Promise<void>;

export function GitRevert(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function GitSaveCredential(arg1:string,arg2:string,arg3:string):Promise<vault.GitCredential>;

export function GitSetDefaultAgent(arg1:string,arg2:string):Promise<void>;

export function GitSetDiffPrefs(arg1:number,arg2:boolean,arg3:boolean):Promise<void>;

export function GitSetIdentity(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<void>;

export function GitSetOpenFiles(arg1:string,arg2:Array<string>):Promise<void>;

export function GitSetPaneWidths(arg1:number,arg2:number):Promise<void>;

export function GitSetPinnedBranches(arg1:string,arg2:Array<string>):Promise<void>;

export function GitSetRemoteURL(arg1:string,arg2:string,arg3:string):Promise<void>;

export function GitSetUpstream(arg1:string,arg2:string,arg3:string):Promise<void>;

export function GitStage(arg1:string,arg2:Array<string>):Promise<void>;

export function GitStageAll(arg1:string):Promise<void>;

export function GitStashApply(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function GitStashDiff(arg1:string,arg2:string):Promise<string>;

export function GitStashDrop(arg1:string,arg2:string):Promise<void>;

export function GitStashPush(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function GitStashes(arg1:string):Promise<Array<git.Stash>>;

export function GitStatus(arg1:string):Promise<git.RepoStatus>;

export function GitTags(arg1:string):Promise<Array<git.Tag>>;

export function GitUnsetUpstream(arg1:string,arg2:string):Promise<void>;

export function GitUnstage(arg1:string,arg2:Array<string>):Promise<void>;

export function GitUpsertMCPServer(arg1:string,arg2:mcpconf.ServerInput):Promise<void>;

export function GitWorktrees(arg1:string):Promise<Array<git.Worktree>>;

export function GitWriteWorkFile(arg1:string,arg2:string,arg3:string,arg4:number):Promise<number>;

export function HasOpenTransaction(arg1:string):Promise<boolean>;

export function InitializeVault(arg1:string):Promise<void>;

export function IsVaultInitialized():Promise<boolean>;

export function ListAgentChats(arg1:string):Promise<Array<vault.AgentChat>>;

export function ListAgents():Promise<Array<agents.Agent>>;

export function ListAllAgentChats():Promise<Array<vault.AgentChat>>;

export function ListConnections():Promise<Array<vault.ConnectionSummary>>;

export function ListExplainHistory(arg1:string,arg2:number):Promise<Array<vault.ExplainHistoryEntry>>;

export function ListFolders():Promise<Array<vault.Folder>>;

export function ListMongoCollections(arg1:string,arg2:string,arg3:boolean):Promise<Array<db.MongoCollectionInfo>>;

export function ListMongoDatabases(arg1:string):Promise<Array<db.MongoDatabaseInfo>>;

export function ListMongoDocuments(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number,arg6:number):Promise<Array<string>>;

export function ListNotes():Promise<Array<vault.NoteSummary>>;

export function ListQueryHistory(arg1:string,arg2:number):Promise<Array<vault.HistoryEntry>>;

export function ListRecentFiles():Promise<Array<vault.RecentFile>>;

export function ListRedisKeys(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number):Promise<db.RedisScanPage>;

export function ListSSHKeys():Promise<Array<vault.SSHKeySummary>>;

export function ListSchemas(arg1:string,arg2:boolean):Promise<Array<string>>;

export function ListSchemasForNewConnection(arg1:main.ConnectionInput):Promise<Array<string>>;

export function ListSftpDir(arg1:string,arg2:string):Promise<Array<sftpx.FileEntry>>;

export function ListShells():Promise<Array<localterm.Shell>>;

export function ListSshHistory(arg1:string,arg2:number):Promise<Array<vault.SshHistoryEntry>>;

export function ListSshSnippets():Promise<Array<vault.SshSnippet>>;

export function ListTools():Promise<Array<mcpserver.ToolInfo>>;

export function LocalShellLabel(arg1:string):Promise<string>;

export function MCPServerStatus():Promise<main.MCPStatus>;

export function MakeSftpDir(arg1:string,arg2:string):Promise<void>;

export function MoveConnectionToFolder(arg1:string,arg2:string):Promise<void>;

export function MoveFolder(arg1:string,arg2:string):Promise<void>;

export function MoveSshSnippetToFolder(arg1:string,arg2:string):Promise<void>;

export function NoteBacklinks(arg1:string):Promise<Array<vault.NoteLink>>;

export function NoteLinks(arg1:string):Promise<Array<vault.NoteLink>>;

export function NoteStatsFor(arg1:string):Promise<main.NoteStats>;

export function NoteTags():Promise<Array<vault.NoteTag>>;

export function NoteTitles():Promise<Array<main.NoteTitle>>;

export function NotesGraph():Promise<vault.NoteGraphData>;

export function OpenAgentSession(arg1:string,arg2:string,arg3:string,arg4:number,arg5:number,arg6:boolean):Promise<void>;

export function OpenLocalTerminal(arg1:string,arg2:string,arg3:number,arg4:number):Promise<void>;

export function OpenLocalTerminalAt(arg1:string,arg2:number,arg3:number):Promise<void>;

export function OpenSQLFileDialog():Promise<main.FileContent>;

export function OpenSQLFilePath(arg1:string):Promise<main.FileContent>;

export function OpenSSHTerminal(arg1:string,arg2:number,arg3:number):Promise<void>;

export function OpenSftpBrowse(arg1:string,arg2:string):Promise<string>;

export function PersistRedisKey(arg1:string,arg2:string):Promise<void>;

export function PickAutoBackupFolder():Promise<string>;

export function PickSQLiteFile():Promise<string>;

export function PickVaultBackupFile(arg1:string):Promise<string>;

export function PickVaultBackupFileFirstRun():Promise<string>;

export function PrimeSchemaIndex(arg1:string):Promise<sqlintel.Status>;

export function PushRedisListValue(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ReadRedisStream(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function ReadSftpFileForEdit(arg1:string,arg2:string):Promise<sftpx.RemoteFile>;

export function RecordCompletionUse(arg1:string,arg2:string,arg3:string):Promise<void>;

export function RedisTransactionStatus(arg1:string):Promise<Record<string, any>>;

export function RegenerateProjectDocs(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ReleasePagedResult(arg1:string):Promise<void>;

export function RemoveRedisListIndex(arg1:string,arg2:string,arg3:number):Promise<void>;

export function RemoveRedisSetMember(arg1:string,arg2:string,arg3:string):Promise<void>;

export function RemoveRedisZSetMember(arg1:string,arg2:string,arg3:string):Promise<void>;

export function RenameAgentChat(arg1:string,arg2:string):Promise<void>;

export function RenameFolder(arg1:string,arg2:string):Promise<void>;

export function RenameSSHKey(arg1:string,arg2:string):Promise<void>;

export function RenameSftpPath(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ReorderFolder(arg1:string,arg2:string):Promise<void>;

export function ReplaceMongoDocument(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function ResetAgentChat(arg1:string):Promise<void>;

export function ResizeLocalTerminal(arg1:string,arg2:number,arg3:number):Promise<void>;

export function ResizeSSHTerminal(arg1:string,arg2:number,arg3:number):Promise<void>;

export function ResolveJoinCondition(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<Array<sqlintel.JoinCondition>>;

export function RespondAgentApproval(arg1:string,arg2:boolean,arg3:string):Promise<void>;

export function RestoreVaultBackupFirstRun(arg1:string,arg2:string):Promise<void>;

export function RestoreVaultBackupFromFile(arg1:string,arg2:string):Promise<void>;

export function ResumeAgentChat(arg1:string,arg2:string):Promise<void>;

export function RevealConnectionPassword(arg1:string,arg2:string):Promise<string>;

export function RollbackTransaction(arg1:string):Promise<void>;

export function RunRedisLuaScript(arg1:string,arg2:string,arg3:Array<string>,arg4:Array<string>):Promise<redisquery.LuaResult>;

export function SSHCwd(arg1:string):Promise<string>;

export function SSHKeyUsage(arg1:string):Promise<Array<string>>;

export function SSHTail(arg1:string,arg2:number):Promise<Array<string>>;

export function SampleMongoFields(arg1:string,arg2:string,arg3:string):Promise<Array<db.MongoFieldInfo>>;

export function SaveChatAttachment(arg1:string,arg2:string):Promise<string>;

export function SaveConnection(arg1:main.ConnectionInput,arg2:boolean):Promise<vault.ConnectionSummary>;

export function SaveDDLToFile(arg1:string,arg2:string):Promise<string>;

export function SaveNoteImage(arg1:string,arg2:string):Promise<string>;

export function SaveSQLFile(arg1:string,arg2:string):Promise<void>;

export function SaveSQLFileAs(arg1:string,arg2:string):Promise<string>;

export function SaveSSHKey(arg1:string,arg2:string,arg3:string):Promise<vault.SSHKeySummary>;

export function SearchNotesSmart(arg1:string,arg2:number):Promise<Array<vault.NoteHit>>;

export function SendAgentChat(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:string,arg9:Array<string>):Promise<void>;

export function SetAgentActive(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetAgentChatContext(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetAgentChatSettings(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function SetAgentCommand(arg1:string,arg2:string):Promise<void>;

export function SetAgentKey(arg1:string,arg2:string):Promise<void>;

export function SetAgentLayout(arg1:string,arg2:number):Promise<void>;

export function SetAutoBackupEnabled(arg1:boolean):Promise<void>;

export function SetAutoBackupIntervalHours(arg1:number):Promise<void>;

export function SetAutoSaveEnabled(arg1:boolean):Promise<void>;

export function SetAutoSaveIntervalSeconds(arg1:number):Promise<void>;

export function SetCollapsedSidebarModules(arg1:Array<string>):Promise<void>;

export function SetConnectionSchemas(arg1:string,arg2:Array<string>):Promise<void>;

export function SetEditorHeight(arg1:number):Promise<void>;

export function SetEditorTheme(arg1:string):Promise<void>;

export function SetGitLayout(arg1:string,arg2:number,arg3:string,arg4:boolean,arg5:boolean):Promise<void>;

export function SetGitPanelSessions(arg1:Array<vault.GitPanelSession>):Promise<void>;

export function SetLocalShell(arg1:string):Promise<void>;

export function SetMCPServerEnabled(arg1:boolean):Promise<void>;

export function SetNoteFolder(arg1:string,arg2:string):Promise<void>;

export function SetNotePrivacy(arg1:string,arg2:boolean):Promise<void>;

export function SetNotesLastOpen(arg1:string):Promise<void>;

export function SetOpenTabs(arg1:Array<vault.OpenTabInfo>):Promise<void>;

export function SetQueryPageSize(arg1:number):Promise<void>;

export function SetRedisHashField(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function SetRedisJSONValue(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetRedisKeyTTL(arg1:string,arg2:string,arg3:number):Promise<void>;

export function SetRedisListIndex(arg1:string,arg2:string,arg3:number,arg4:string):Promise<void>;

export function SetRedisStringValue(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetRememberMasterKey(arg1:boolean):Promise<void>;

export function SetSidebarCollapsed(arg1:boolean):Promise<void>;

export function SetSshHistoryEnabled(arg1:boolean):Promise<void>;

export function SetSshTerminalTheme(arg1:string):Promise<void>;

export function SetTerminalFontSize(arg1:number):Promise<void>;

export function SetTheme(arg1:string):Promise<void>;

export function SftpHomeDir(arg1:string):Promise<string>;

export function SftpPathPermissions(arg1:string,arg2:string):Promise<sftpx.PermInfo>;

export function SshHistoryEnabled():Promise<boolean>;

export function StartSftpTransfer(arg1:main.SftpTransferInput):Promise<void>;

export function StopRedisMonitor(arg1:string):Promise<void>;

export function SubscribeRedisChannels(arg1:string,arg2:string,arg3:Array<string>,arg4:Array<string>):Promise<void>;

export function SuggestInlineSQL(arg1:sqlintel.Request):Promise<string>;

export function SyncSchemaMetadata(arg1:string,arg2:string):Promise<db.SchemaMetadata>;

export function TestConnection(arg1:main.ConnectionInput):Promise<void>;

export function TouchAgentChat(arg1:string,arg2:string):Promise<void>;

export function TryAutoUnlock():Promise<boolean>;

export function UnlockVault(arg1:string):Promise<void>;

export function UpdateConnection(arg1:string,arg2:main.ConnectionInput,arg3:boolean):Promise<vault.ConnectionSummary>;

export function UpdateNote(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function UpdateSshSnippet(arg1:string,arg2:string,arg3:string):Promise<void>;

export function WriteLocalTerminal(arg1:string,arg2:string):Promise<void>;

export function WriteSSHTerminal(arg1:string,arg2:string):Promise<void>;

export function WriteSftpFileFromEdit(arg1:string,arg2:string,arg3:string,arg4:number):Promise<number>;
